# Generated by Django 3.1.7 on 2021-04-08 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_follow_likes_post_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
